name: HuskSync
version: ${version}
main: net.william278.husksync.BukkitHuskSync
api-version: 1.16
author: William278
description: 'A modern, cross-server player data synchronization system'
website: 'https://william278.net'
softdepend:
  - MysqlPlayerDataBridge
  - Plan
libraries:
  - 'mysql:mysql-connector-java:8.0.29'
  - 'org.xerial.snappy:snappy-java:1.1.8.4'
  - 'dev.dejvokep:boosted-yaml:1.2'
commands:
  husksync:
    usage: '/husksync <update/info/reload/migrate>'
    description: 'Manage the HuskSync plugin'
  userdata:
    usage: '/userdata <view/list/delete/restore> <username> [version_uuid]'
    description: 'View, manage & restore player userdata'
  inventory:
    usage: '/inventory <username> [version_uuid]'
    description: 'View & edit a player''s inventory'
  enderchest:
    usage: '/enderchest <username> [version_uuid]'
    description: 'View & edit a player''s Ender Chest'