name: 'HuskSync'
version: '${version}'
main: 'net.william278.husksync.BukkitHuskSync'
api-version: 1.17
author: 'William278'
description: '${description}'
website: 'https://william278.net'
folia-supported: true
softdepend:
  - 'packetevents'
  - 'ProtocolLib'
  - 'MysqlPlayerDataBridge'
  - 'Plan'
libraries:
  - 'redis.clients:jedis:${jedis_version}'
  - 'com.mysql:mysql-connector-j:${mysql_driver_version}'
  - 'org.mariadb.jdbc:mariadb-java-client:${mariadb_driver_version}'
  - 'org.postgresql:postgresql:${postgres_driver_version}'
  - 'org.mongodb:mongodb-driver-sync:${mongodb_driver_version}'
  - 'org.xerial.snappy:snappy-java:${snappy_version}'