#!/bin/bash

echo "mvn-installing mpdbdataconverter..."
curl "https://github.com/WiIIiam278/MPDBDataConverter/releases/download/1.0/mpdbdataconverter-1.0.jar" > "mpdbdataconverter-1.0.jar"
mvn "install:install-file" "mpdbdataconverter-1.0.jar" "-DgroupId=net.william278" "-DartifactId=mpdbdataconverter" "-Dversion=1.0" "-Dpackaging=jar" "-DgeneratePom=true" "-e"