#  ------------------------------
# |        HuskSync Config       |
# |    Developed by William278   |
#  ------------------------------
# Documentation available at: https://william278.net/docs/husksync/Setup

language: 'en-gb'
check_for_updates: true
cluster_id: ''
debug_logging: false

database:
  credentials:
    host: 'localhost'
    port: 3306
    database: 'HuskSync'
    username: 'root'
    password: 'pa55w0rd'
    params: '?autoReconnect=true&useSSL=false'
  connection_pool:
    maximum_pool_size: 10
    minimum_idle: 10
    maximum_lifetime: 1800000
    keepalive_time: 0
    connection_timeout: 5000
  table_names:
    users_table: 'husksync_users'
    user_data_table: 'husksync_user_data'

redis:
  credentials:
    host: 'localhost'
    port: 6379
    password: ''
  use_ssl: false

synchronization:
  server_id: 'node-1'
  max_user_data_snapshots: 5
  save_on_world_save: true
  compress_data: true
  save_dead_player_inventories: true
  network_latency_milliseconds: 500
  features:
    inventories: true
    ender_chests: true
    health: true
    max_health: true
    hunger: true
    experience: true
    potion_effects: true
    advancements: true
    game_mode: true
    statistics: true
    persistent_data_container: true
    location: false

config_version: 1