name: 'HuskSync'
description: '${description}'
author: 'William278'
website: 'https://william278.net/'
main: 'net.william278.husksync.PaperHuskSync'
loader: 'net.william278.husksync.PaperHuskSyncLoader'
version: '${version}'
api-version: '1.19'
dependencies:
  server:
    MysqlPlayerDataBridge:
      required: false
      load: BEFORE
      join-classpath: true
    Plan:
      required: false
      load: BEFORE
      join-classpath: true